let characters=[];let state={coins:100,lastDaily:null,owned:{}};const $=s=>document.querySelector(s);
async function init(){try{characters=await fetch("data/characters.json").then(r=>r.json())}catch(e){}loadState();dailyCoins();render()}
function loadState(){try{let x=JSON.parse(localStorage.getItem("animecards-state"));if(x)state={...state,...x}}catch(e){}}
function save(){localStorage.setItem("animecards-state",JSON.stringify(state))}
function dailyCoins(){let today=new Date().toISOString().slice(0,10);if(state.lastDaily!==today){state.coins+=100;state.lastDaily=today;save()}updateWallet()}
function updateWallet(){$("#coins").textContent=state.coins}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function image(c){return c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:""}
function cardHTML(c){return `<div class="card"><div class="art">${image(c)}<div class="placeholder" style="display:${c.image?'none':'grid'}">${esc((c.name||"?")[0])}</div><span class="rarity">${"★".repeat(c.rarity||1)}</span></div><div class="info"><div><strong>${esc(c.name)}</strong><small>${esc(c.series)}</small></div></div></div>`}
function render(){updateWallet();$("#collectionCount").textContent=Object.keys(state.owned).length+" / "+characters.length+" unique";$("#collectionGrid").innerHTML=characters.map(c=>{let n=state.owned[c.id]||0;return `<div class="card"><div class="art">${n?image(c):'<div class="placeholder">?</div>'}<span class="rarity">${n?"★".repeat(c.rarity||1):"???"}</span></div><div class="info"><div><strong>${n?esc(c.name):"???"}</strong><small>${n?esc(c.series):"Not discovered"}</small></div><span class="owned">${n?"x"+n:"LOCKED"}</span></div></div>`}).join("");let first=characters.find(c=>state.owned[c.id])||characters[0];if(first)$("#heroCard").innerHTML=cardHTML(first)}
function randomCard(){let pool=characters.flatMap(c=>Array(Math.max(1,7-(c.rarity||1))).fill(c));return pool[Math.floor(Math.random()*pool.length)]}
function openPack(){if(state.coins<10){alert("You need 10 coins!");return}if(!characters.length)return;state.coins-=10;let pulled=[];let duplicateCoins=0;for(let i=0;i<3;i++){let c=randomCard();pulled.push(c);state.owned[c.id]=(state.owned[c.id]||0)+1;if(state.owned[c.id]>1)duplicateCoins+=5}state.coins+=duplicateCoins;save();render();$("#newCards").innerHTML=pulled.map(c=>`<div class="new-card">${cardHTML(c)}</div>`).join("");$("#packResult").textContent=duplicateCoins?`Duplicates converted to +${duplicateCoins} coins.`:"No duplicates this time!";$("#opening").classList.remove("hidden")}
function closeOpening(){$("#opening").classList.add("hidden")}init();